# Generated by Django 5.1.2 on 2025-04-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('액션', '액션'), ('코미디', '코미디'), ('드라마', '드라마'), ('SF', 'SF'), ('로맨스', '로맨스'), ('스릴러', '스릴러'), ('호러', '호러'), ('애니메이션', '애니메이션'), ('다큐멘터리', '다큐멘터리'), ('판타지', '판타지')], default='드라마', max_length=20),
        ),
    ]
